### ISSUE TITLE
* (wildcard) in rm path

### ISSUE THREAD

**Issue by theRAAPster** [flohoss/gocron#15]
Apologies in advance, got a couple more issues I'm going to be spamming you with today.

I have a job that looks like this:

```
  - name: Test Job
    envs:
      - key: TEST_URL
        value: 'https://raw.githubusercontent.com/flohoss/gocron/refs/heads/main/README.md'
      - key: BACKUP_PATH
        value: '/app/config/test'
    commands:
      # Remove old backups. Force so rm doesn't error if the directory is empty.
      - command: rm -r -f ${BACKUP_PATH}/*
      - command: curl -k -X GET "${TEST_URL}" -o ${BACKUP_PATH}/backup.md
```

The rm command in the first step does nothing however. Changing that command to be `rm -r -i ${BACKUP_PATH}/*` gets me the following error:

```
2025-04-06 14:14:15: Executing command: "rm -r -i /app/config/test/*"
2025-04-06 14:14:15: rm: can't remove '/app/config/test/*': No such file or directory
```

There is a file that exists that can be seen in that path in the gocron container though, and running rm works:

```
/app $ ls -l /app/config/test
total 12
-rw-r--r--    1 1000     1000          9476 Apr  6 14:11 backup.md

/app $ rm -r -i /app/config/test/*
rm: remove '/app/config/test/backup.md'? y

/app $ ls -l /app/config/test
total 0
```

If I change the command to be `rm -r -f ${BACKUP_PATH/backup.md` gocron is able to successfully delete the file, which leads me to believe the issue is with the wildcard. Are wildcards supposed to be supported or do they need to be escaped in some way? It is not crucial for this job at this time (hopefully changing when I submit my next issue), but I do have other jobs where I don't have control over the name of the backup file and it gets created with a date and time stamp.

EDIT: Updated with a job that should be easier for you to replicate the issue. Make sure to create the test directory in your gocron config directory first.
